# Generated by Django 5.2.1 on 2025-05-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('manager', 'Manager'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='viewer', max_length=10),
        ),
    ]
