# Generated by Django 5.2.1 on 2025-05-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emipayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leasecontract',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='leasecontract',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='loancontract',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='loancontract',
            name='customer',
        ),
        migrations.DeleteModel(
            name='EMIPayment',
        ),
        migrations.DeleteModel(
            name='LeaseContract',
        ),
        migrations.DeleteModel(
            name='LoanContract',
        ),
    ]
