# Generated by Django 5.2.1 on 2025-05-26 07:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_leasecontract_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('interest_rate', models.FloatField(default=0.0)),
                ('total_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('tenure_months', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(84)])),
                ('payment_option', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=25)),
                ('loan_status', models.CharField(choices=[('pending_approval', 'Approval Pending'), ('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted')], default='pending_approval', max_length=25)),
                ('loan_purpose', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business'), ('education', 'Education'), ('home_improvement', 'Home Improvement'), ('debt_consolidation', 'Debt Consolidation'), ('auto', 'Auto'), ('medical', 'Medical'), ('vacation', 'Vacation'), ('wedding', 'Wedding'), ('other', 'Other')], default='personal', max_length=25)),
                ('is_islamic', models.BooleanField(default=False)),
                ('markup_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('passport_or_nid', models.FileField(blank=True, null=True, upload_to='documents/id/')),
                ('bank_statement', models.FileField(blank=True, null=True, upload_to='documents/bank_statements/')),
                ('account_certificate', models.FileField(blank=True, null=True, upload_to='documents/account_certificates/')),
                ('stamp_paper_signed', models.FileField(blank=True, null=True, upload_to='documents/stamp_papers/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('loan_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='core.loancontract')),
            ],
            options={
                'ordering': ['due_date'],
                'unique_together': {('loan_contract', 'installment_number')},
            },
        ),
    ]
